### PR TITLE
fix some wrong runinfo pvs

### LINKED ISSUE #103: DAE timing source
As a member of DSG I'd like to have "DAE timing source" available on the new webdash

### PR DESCRIPTION
**Pull request by rerpha**
closes #103 
This PR: 
corrects some wrong runinfo PVs
truncates their values
moves a lot of logic out of the instrumentdata class, which isn't easy to test, to individual functions that are.

### CODE REVIEW

File: app/components/Instrument.ts [hunk 1]
```diff
@@ -71,10 +85,6 @@ export class Instrument {
         pvaddress: `${this.prefix}DAE:RUNNUMBER`,
         human_readable_name: "Run number",
       },
-      {
-        pvaddress: `${this.prefix}DAE:STARTTIME`,
-        human_readable_name: "Start number",
-      },
```
Comment (Tom-Willemsen) [inline app/components/Instrument.ts:77]: Won't let me comment on the actual line, but `title`/`users` not showing in the table for me.

Comment (rerpha) [reply app/components/Instrument.ts:77]: hmm yes and i know why - the dashboard PV "steals" the update because of this: 
```
const pv =
        findPVInDashboard(currentInstrument.dashboard, updatedPVName) ||
        findPVByAddress(currentInstrument.runInfoPVs, updatedPVName) ||
        findPVInGroups(
          currentInstrument.groups,
          currentInstrument.prefix,
          updatedPVName,
        );
```

as the dashboard is before the runinfo. 

will have a think. maybe it's not useful having it twice anyway?

Comment (Tom-Willemsen) [reply app/components/Instrument.ts:77]: I'm fine with deleting it here if it's always part of the top panel anyway.

**Review by Tom-Willemsen — APPROVED** [review]
